[package]
name = "rustfinder"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0"
image = { version = "0.25", features = ["gif", "png"] }
ndarray = "0.15"
rand = { version = "0.8", features = ["std"] }
ordered-float = "3.0"
